[package]
name = "rust-codec"
version = "0.1.0"
authors = ["willcl-ark <will8clark@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.2"